camera:
  height: 720
  rotation_deg: 0
  width: 1280
camera2:
  rotation_deg: 0
head_tracking:
  face_tracking_enabled: false
  random_motion_enabled: false
servo:
  enabled: true
  soft_max_deg: 360.0
  soft_min_deg: 1.0
