camera:
  height: 720
  rotation_deg: 270
  width: 1280
camera2:
  rotation_deg: 90
head_tracking:
  face_tracking_enabled: true
  random_motion_enabled: true
servo:
  enabled: true
  soft_max_deg: 360.0
  soft_min_deg: 1.0
