camera:
  height: 480
  rotation_deg: 270
  width: 640
camera2:
  rotation_deg: 90
head_tracking:
  face_tracking_enabled: true
  random_motion_enabled: false
servo:
  enabled: true
  soft_max_deg: 270.0
  soft_min_deg: 90.0
